### ISSUE TITLE
Analyse logs and its severity level

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-payone-integration#114]
Currently service logs a lot and it is not always clear why and if it is serious issue. Some examples:
- Unclear why and if it should be logged at all

```
WARN [qtp2091327366-26] (PaypalRequestFactory.java:101) - Could not fully map payment with ID feab85c0-ed53-4e01-9141-215c83eebaee
```
- Sensitive user data should not be always logged within `Payone POST request parameters` message as INFO. It might be logged on payone error response as WARN.
- `Payone POST response` may contain sensitive bank data and should be logged on payone error only as WARN.
- Does it make sense to log it? 

```
INFO [DefaultQuartzScheduler_Worker-8] (ScheduledJob.java:46) - Could not dispatch payment with ID "6a1aec4b-70ab-461d-8f8a-dd16fea6b1dd": The payment is currently processed by someone else.
```
- Long stack traces should be avoided and root cause logged as error

```
2016-08-25T07:10:00.355365823Z ERROR [DefaultQuartzScheduler_Worker-5] (JobRunShell.java:211) - Job DEFAULT.6da64b5bd2ee-b936f931-77c6-4aab-8b9d-93c2965930a4 threw an unhandled Exception:  
2016-08-25T07:10:00.355407616Z io.sphere.sdk.http.HttpException: The underlying HTTP client detected a problem. 
2016-08-25T07:10:00.355415353Z  at io.sphere.sdk.http.HttpClientAdapterBase.lambda$execute$12(HttpClientAdapterBase.java:50) 
2016-08-25T07:10:00.355420998Z  at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) 
2016-08-25T07:10:00.355426352Z  at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778) 
2016-08-25T07:10:00.355431666Z  at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140) 
2016-08-25T07:10:00.355445295Z  at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:110) 
2016-08-25T07:10:00.355450350Z  at io.sphere.sdk.http.HttpClientAdapterBase.execute(HttpClientAdapterBase.java:43) 
2016-08-25T07:10:00.355455614Z  at io.sphere.sdk.client.SphereClientImpl.execute(SphereClientImpl.java:71) 
2016-08-25T07:10:00.355460301Z  at io.sphere.sdk.client.SphereClientImpl.lambda$execute$26(SphereClientImpl.java:39) 
2016-08-25T07:10:00.355464969Z  at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) 
2016-08-25T07:10:00.355469575Z  at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) 
2016-08-25T07:10:00.355474145Z  at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110) 
2016-08-25T07:10:00.355478782Z  at io.sphere.sdk.client.SphereClientImpl.execute(SphereClientImpl.java:39) 
2016-08-25T07:10:00.355483323Z  at io.sphere.sdk.client.BlockingSphereClientImpl.execute(BlockingSphereClientImpl.java:30) 
2016-08-25T07:10:00.355488101Z  at io.sphere.sdk.client.BlockingSphereClientImpl.executeBlocking(BlockingSphereClientImpl.java:40) 
2016-08-25T07:10:00.355492782Z  at io.sphere.sdk.client.BlockingSphereClientImpl.executeBlocking(BlockingSphereClientImpl.java:35) 
2016-08-25T07:10:00.355497480Z  at com.commercetools.pspadapter.payone.domain.ctp.CommercetoolsQueryExecutor.consumeAllMessages(CommercetoolsQueryExecutor.java:110) 
2016-08-25T07:10:00.355502200Z  at com.commercetools.pspadapter.payone.domain.ctp.CommercetoolsQueryExecutor.consumePaymentCreatedMessages(CommercetoolsQueryExecutor.java:86) 
2016-08-25T07:10:00.355506887Z  at com.commercetools.pspadapter.payone.ScheduledJob.execute(ScheduledJob.java:53) 
2016-08-25T07:10:00.355511979Z  at org.quartz.core.JobRunShell.run(JobRunShell.java:202) 
2016-08-25T07:10:00.355516410Z  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) 
2016-08-25T07:10:00.355521006Z Caused by: java.util.concurrent.CompletionException: java.net.UnknownHostException: api.sphere.io: unknown error 
2016-08-25T07:10:00.355525463Z  at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) 
2016-08-25T07:10:00.355529822Z  at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) 
2016-08-25T07:10:00.355534396Z  at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593) 
2016-08-25T07:10:00.355538874Z  at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) 
2016-08-25T07:10:00.355543410Z  at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617) 
2016-08-25T07:10:00.355547878Z  at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1993) 
2016-08-25T07:10:00.355552395Z  at io.sphere.sdk.http.DefaultAsyncHttpClient2_0AdapterImpl.executeDelegate(DefaultAsyncHttpClient2_0AdapterImpl.java:21) 
2016-08-25T07:10:00.355556926Z  at io.sphere.sdk.http.HttpClientAdapterBase.execute(HttpClientAdapterBase.java:37) 
2016-08-25T07:10:00.355567611Z  ... 14 more 
2016-08-25T07:10:00.355572241Z Caused by: java.net.UnknownHostException: api.sphere.io: unknown error 
2016-08-25T07:10:00.355576725Z  at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) 
2016-08-25T07:10:00.355581240Z  at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) 
2016-08-25T07:10:00.355585885Z  at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) 
2016-08-25T07:10:00.355590454Z  at java.net.InetAddress.getAllByName0(InetAddress.java:1276) 
2016-08-25T07:10:00.355594963Z  at java.net.InetAddress.getAllByName(InetAddress.java:1192) 
2016-08-25T07:10:00.355599438Z  at java.net.InetAddress.getAllByName(InetAddress.java:1126) 
2016-08-25T07:10:00.355603896Z  at io.netty.resolver.DefaultNameResolver.doResolveAll(DefaultNameResolver.java:49) 
2016-08-25T07:10:00.355608423Z  at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:81) 
2016-08-25T07:10:00.355612947Z  at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:72) 
2016-08-25T07:10:00.355617412Z  at org.asynchttpclient.resolver.RequestHostnameResolver.resolve(RequestHostnameResolver.java:64) 
2016-08-25T07:10:00.355621898Z  at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:274) 
2016-08-25T07:10:00.355626353Z  at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:135) 
2016-08-25T07:10:00.355630897Z  at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:106) 
2016-08-25T07:10:00.355636734Z  at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:220) 
2016-08-25T07:10:00.355641497Z  at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:188) 
2016-08-25T07:10:00.355646246Z  at io.sphere.sdk.http.DefaultAsyncHttpClient2_0AdapterImpl.executeDelegate(DefaultAsyncHttpClient2_0AdapterImpl.java:20) 
2016-08-25T07:10:00.355650923Z  ... 15 more 
2016-08-25T07:10:00.357744911Z ERROR [DefaultQuartzScheduler_Worker-5] (QuartzScheduler.java:2425) - Job (DEFAULT.6da64b5bd2ee-b936f931-77c6-4aab-8b9d-93c2965930a4 threw an exception. 
2016-08-25T07:10:00.357759564Z org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: io.sphere.sdk.http.HttpException: The underlying HTTP client detected a problem.] 
2016-08-25T07:10:00.357765839Z  at org.quartz.core.JobRunShell.run(JobRunShell.java:213) 
2016-08-25T07:10:00.357770657Z  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) 
2016-08-25T07:10:00.357781588Z Caused by: io.sphere.sdk.http.HttpException: The underlying HTTP client detected a problem. 
2016-08-25T07:10:00.357794061Z  at io.sphere.sdk.http.HttpClientAdapterBase.lambda$execute$12(HttpClientAdapterBase.java:50) 
2016-08-25T07:10:00.357805597Z  at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) 
2016-08-25T07:10:00.357810794Z  at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778) 
2016-08-25T07:10:00.357815742Z  at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140) 
2016-08-25T07:10:00.357820436Z  at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:110) 
2016-08-25T07:10:00.357824984Z  at io.sphere.sdk.http.HttpClientAdapterBase.execute(HttpClientAdapterBase.java:43) 
2016-08-25T07:10:00.357829389Z  at io.sphere.sdk.client.SphereClientImpl.execute(SphereClientImpl.java:71) 
2016-08-25T07:10:00.357833827Z  at io.sphere.sdk.client.SphereClientImpl.lambda$execute$26(SphereClientImpl.java:39) 
2016-08-25T07:10:00.357838479Z  at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) 
2016-08-25T07:10:00.357843126Z  at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) 
2016-08-25T07:10:00.357847701Z  at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110) 
2016-08-25T07:10:00.357852211Z  at io.sphere.sdk.client.SphereClientImpl.execute(SphereClientImpl.java:39) 
2016-08-25T07:10:00.357856748Z  at io.sphere.sdk.client.BlockingSphereClientImpl.execute(BlockingSphereClientImpl.java:30) 
2016-08-25T07:10:00.357861658Z  at io.sphere.sdk.client.BlockingSphereClientImpl.executeBlocking(BlockingSphereClientImpl.java:40) 
2016-08-25T07:10:00.357866149Z  at io.sphere.sdk.client.BlockingSphereClientImpl.executeBlocking(BlockingSphereClientImpl.java:35) 
2016-08-25T07:10:00.357870831Z  at com.commercetools.pspadapter.payone.domain.ctp.CommercetoolsQueryExecutor.consumeAllMessages(CommercetoolsQueryExecutor.java:110) 
2016-08-25T07:10:00.357875436Z  at com.commercetools.pspadapter.payone.domain.ctp.CommercetoolsQueryExecutor.consumePaymentCreatedMessages(CommercetoolsQueryExecutor.java:86) 
2016-08-25T07:10:00.357885197Z  at com.commercetools.pspadapter.payone.ScheduledJob.execute(ScheduledJob.java:53) 
2016-08-25T07:10:00.357894466Z  at org.quartz.core.JobRunShell.run(JobRunShell.java:202) 
2016-08-25T07:10:00.357902232Z  ... 1 more 
2016-08-25T07:10:00.357908052Z Caused by: java.util.concurrent.CompletionException: java.net.UnknownHostException: api.sphere.io: unknown error 
2016-08-25T07:10:00.357912686Z  at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) 
2016-08-25T07:10:00.357917098Z  at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) 
2016-08-25T07:10:00.357921557Z  at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593) 
2016-08-25T07:10:00.357926121Z  at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) 
2016-08-25T07:10:00.357930730Z  at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617) 
2016-08-25T07:10:00.357935322Z  at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1993) 
2016-08-25T07:10:00.357947407Z  at io.sphere.sdk.http.DefaultAsyncHttpClient2_0AdapterImpl.executeDelegate(DefaultAsyncHttpClient2_0AdapterImpl.java:21) 
2016-08-25T07:10:00.357952413Z  at io.sphere.sdk.http.HttpClientAdapterBase.execute(HttpClientAdapterBase.java:37) 
2016-08-25T07:10:00.357956924Z  ... 14 more 
2016-08-25T07:10:00.357965845Z Caused by: java.net.UnknownHostException: api.sphere.io: unknown error 
2016-08-25T07:10:00.357970621Z  at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) 
2016-08-25T07:10:00.357975261Z  at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) 
2016-08-25T07:10:00.357979950Z  at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) 
2016-08-25T07:10:00.357984720Z  at java.net.InetAddress.getAllByName0(InetAddress.java:1276) 
2016-08-25T07:10:00.357989234Z  at java.net.InetAddress.getAllByName(InetAddress.java:1192) 
2016-08-25T07:10:00.357993690Z  at java.net.InetAddress.getAllByName(InetAddress.java:1126) 
2016-08-25T07:10:00.357998145Z  at io.netty.resolver.DefaultNameResolver.doResolveAll(DefaultNameResolver.java:49) 
2016-08-25T07:10:00.358002666Z  at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:81) 
2016-08-25T07:10:00.358007123Z  at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:72) 
2016-08-25T07:10:00.358011480Z  at org.asynchttpclient.resolver.RequestHostnameResolver.resolve(RequestHostnameResolver.java:64) 
2016-08-25T07:10:00.358016010Z  at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:274) 
2016-08-25T07:10:00.358021998Z  at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:135) 
2016-08-25T07:10:00.358026801Z  at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:106) 
2016-08-25T07:10:00.358031334Z  at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:220) 
2016-08-25T07:10:00.358035782Z  at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:188) 
2016-08-25T07:10:00.358040297Z  at io.sphere.sdk.http.DefaultAsyncHttpClient2_0AdapterImpl.executeDelegate(DefaultAsyncHttpClient2_0AdapterImpl.java:20)
```

**Comment by salander85** [comment]
Done.
